In [2]:
import os
from datetime import datetime

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
file_path = "../data/silver/flight_silver_20260422.csv"

In [4]:
df = pd.read_csv(file_path)

df.head()

,icao24,origin_country,latitude,longitude,time_position,last_contact,velocity,vertical_rate,true_track,baro_altitude,on_ground
0,a5f852,United States,40.4558,-104.9981,1.776864e+09,1776863955,2.57,NaN,0.00,NaN,True
1,3ffc29,Germany,48.4362,12.2551,1.776864e+09,1776864081,46.71,-0.33,334.56,815.34,False
2,e8027c,Chile,-16.1126,-54.5891,1.776864e+09,1776864082,243.44,0.00,284.56,10363.20,False
3,a58211,United States,30.7822,-85.0609,1.776864e+09,1776864081,264.69,0.00,92.56,11277.60,False
4,39de4b,France,46.8132,10.0082,1.776864e+09,1776864081,218.92,0.00,285.54,11590.02,False

In [6]:
df['timestamp'] = pd.to_datetime(df['time_position'], unit='s')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10894 entries, 0 to 10893
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   icao24          10894 non-null  str
 1   origin_country  10894 non-null  str
 2   latitude        10783 non-null  float64
 3   longitude       10783 non-null  float64
 4   time_position   10783 non-null  float64
 5   last_contact    10894 non-null  int64
 6   velocity        10888 non-null  float64
 7   vertical_rate   9978 non-null   float64
 8   true_track      10894 non-null  float64
 9   baro_altitude   9919 non-null   float64
 10  on_ground       10894 non-null  bool
 11  timestamp       10783 non-null  datetime64[s]
dtypes: bool(1), datetime64[s](1), float64(7), int64(1), str(2)
memory usage: 947.0 KB

In [13]:
df.set_index("timestamp", inplace=True)

In [22]:
df.head()

,icao24,origin_country,latitude,longitude,time_position,last_contact,velocity,vertical_rate,true_track,baro_altitude,on_ground,year,month,day,hour,weekday_numeric,is_weekend,is_peak_hour
timestamp,,,,,,,,,,,,,,,,,,
2026-04-22 13:19:15,a5f852,United States,40.4558,-104.9981,1.776864e+09,1776863955,2.57,NaN,0.00,NaN,True,2026.0,4.0,22.0,13.0,2.0,False,1
2026-04-22 13:21:21,3ffc29,Germany,48.4362,12.2551,1.776864e+09,1776864081,46.71,-0.33,334.56,815.34,False,2026.0,4.0,22.0,13.0,2.0,False,1
2026-04-22 13:21:22,e8027c,Chile,-16.1126,-54.5891,1.776864e+09,1776864082,243.44,0.00,284.56,10363.20,False,2026.0,4.0,22.0,13.0,2.0,False,1
2026-04-22 13:21:21,a58211,United States,30.7822,-85.0609,1.776864e+09,1776864081,264.69,0.00,92.56,11277.60,False,2026.0,4.0,22.0,13.0,2.0,False,1
2026-04-22 13:21:21,39de4b,France,46.8132,10.0082,1.776864e+09,1776864081,218.92,0.00,285.54,11590.02,False,2026.0,4.0,22.0,13.0,2.0,False,1

In [21]:
df.index

DatetimeIndex(['2026-04-22 13:19:15', '2026-04-22 13:21:21',
               '2026-04-22 13:21:22', '2026-04-22 13:21:21',
               '2026-04-22 13:21:21', '2026-04-22 13:21:22',
               '2026-04-22 13:21:18', '2026-04-22 13:21:22',
               '2026-04-22 13:21:22', '2026-04-22 13:21:20',
               ...
               '2026-04-22 13:21:21', '2026-04-22 13:21:22',
               '2026-04-22 13:21:21', '2026-04-22 13:21:22',
               '2026-04-22 13:21:21', '2026-04-22 13:21:21',
               '2026-04-22 13:21:21', '2026-04-22 13:17:12',
               '2026-04-22 13:21:21', '2026-04-22 13:21:21'],
              dtype='datetime64[s]', name='timestamp', length=10894, freq=None)

In [17]:
df['year'] = df.index.year
df['month'] = df.index.month
df['day'] = df.index.day
df['hour'] = df.index.hour
# df['weekday'] = df.index.day_name()
df['weekday_numeric'] = df.index.weekday
df['is_weekend'] = df.index.weekday > 4
df['is_peak_hour'] = ((df.index.hour > 8 )& (df.index.hour < 22)).astype(int)

In [18]:
df.head()

,icao24,origin_country,latitude,longitude,time_position,last_contact,velocity,vertical_rate,true_track,baro_altitude,on_ground,year,month,day,hour,weekday_numeric,is_weekend,is_peak_hour
timestamp,,,,,,,,,,,,,,,,,,
2026-04-22 13:19:15,a5f852,United States,40.4558,-104.9981,1.776864e+09,1776863955,2.57,NaN,0.00,NaN,True,2026.0,4.0,22.0,13.0,2.0,False,1
2026-04-22 13:21:21,3ffc29,Germany,48.4362,12.2551,1.776864e+09,1776864081,46.71,-0.33,334.56,815.34,False,2026.0,4.0,22.0,13.0,2.0,False,1
2026-04-22 13:21:22,e8027c,Chile,-16.1126,-54.5891,1.776864e+09,1776864082,243.44,0.00,284.56,10363.20,False,2026.0,4.0,22.0,13.0,2.0,False,1
2026-04-22 13:21:21,a58211,United States,30.7822,-85.0609,1.776864e+09,1776864081,264.69,0.00,92.56,11277.60,False,2026.0,4.0,22.0,13.0,2.0,False,1
2026-04-22 13:21:21,39de4b,France,46.8132,10.0082,1.776864e+09,1776864081,218.92,0.00,285.54,11590.02,False,2026.0,4.0,22.0,13.0,2.0,False,1